# Cloudflare Tunnel Configuration for BSSC RPC Node
# This configuration allows you to expose your BSSC RPC node through Cloudflare Tunnel
# without exposing your server's IP address directly

tunnel: bssc-rpc-tunnel
credentials-file: /home/user/.cloudflared/tunnel-credentials.json

ingress:
  # Main RPC endpoint
  - hostname: your-domain.com
    service: http://localhost:8899
    originRequest:
      httpHostHeader: your-domain.com
      noTLSVerify: false
      keepAliveConnections: 10
      keepAliveTimeout: 30s
      tcpKeepAlive: 30s
      connectTimeout: 30s
      tlsTimeout: 10s
      # Rate limiting
      retries: 3
      # CORS headers
      access:
        required: false
        teamName: ""
      # WebSocket support
      websocketTunnel: true

  # API documentation subdomain
  - hostname: api.your-domain.com
    service: http://localhost:8080  # If you have a separate API docs server
    originRequest:
      httpHostHeader: api.your-domain.com
      noTLSVerify: false

  # Health check endpoint
  - hostname: health.your-domain.com
    service: http://localhost:8899/health
    originRequest:
      httpHostHeader: health.your-domain.com
      noTLSVerify: false

  # Catch-all rule (must be last)
  - service: http_status:404

# Logging configuration
logfile: /var/log/cloudflared/bssc-rpc-tunnel.log
loglevel: info

# Metrics configuration (optional)
metrics: 127.0.0.1:8080

# Autoupdate configuration
autoupdate-freq: 24h
